#!/usr/bin/env bash
# tests/test_consult_init_falls_back_to_available.sh
#
# v0.18.0 regression guard: when only providers-available.txt is
# present (no providers-active.txt — pre-v0.18 user, or user who
# hasn't run selection yet), bin/consult-init.sh's behavior is
# unchanged from v0.17.0.
set -euo pipefail
cd "$(dirname "$0")"
source lib/assert.sh

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
export CLONE_WARS_HOME="$TMP/cw"
mkdir -p "$CLONE_WARS_HOME"

# Stage only providers-available.txt — no providers-active.txt.
cat > "$CLONE_WARS_HOME/providers-available.txt" <<EOF
# generated by test
codex
claude
EOF

INIT="$(cd .. && pwd)/bin/consult-init.sh"
LIB="$(cd .. && pwd)/lib/state.sh"
RH=$(bash -c "source '$LIB'; cw_repo_hash")

TOPIC=$("$INIT" "v018 fallback regression")
TD="$CLONE_WARS_HOME/state/$RH/$TOPIC"

assert_file_exists "$TD/_consult/troopers.txt" "troopers.txt written"
TROOPERS_BODY=$(grep -vE '^[[:space:]]*(#|$)' "$TD/_consult/troopers.txt")
ROW_COUNT=$(echo "$TROOPERS_BODY" | wc -l)
assert_eq "$ROW_COUNT" "2" "all detected providers form the roster"

echo "$TROOPERS_BODY" | grep -qE $'^codex\t'  || { echo "FAIL: codex row missing"  >&2; exit 1; }
echo "$TROOPERS_BODY" | grep -qE $'^claude\t' || { echo "FAIL: claude row missing" >&2; exit 1; }

# Also verify providers-active.txt was NOT created as a side-effect.
[[ ! -f "$CLONE_WARS_HOME/providers-active.txt" ]] \
  || { echo "FAIL: providers-active.txt should not be auto-created" >&2; exit 1; }

pass "bin/consult-init.sh falls back to providers-available.txt when active is absent"
