#!/usr/bin/env bash
# tests/test_consult_init_prefers_active.sh
#
# v0.18.0: bin/consult-init.sh prefers providers-active.txt (user-
# selected) over providers-available.txt (medic-detected). Stage active
# as a strict subset of available; verify the resulting troopers.txt
# matches the active subset.
set -euo pipefail
cd "$(dirname "$0")"
source lib/assert.sh

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
export CLONE_WARS_HOME="$TMP/cw"
mkdir -p "$CLONE_WARS_HOME"

# Stage providers-available.txt with all 3 consult-eligible providers.
cat > "$CLONE_WARS_HOME/providers-available.txt" <<EOF
# generated by test
codex
claude
opencode
EOF

# Stage providers-active.txt as a strict subset (drop opencode).
cat > "$CLONE_WARS_HOME/providers-active.txt" <<EOF
# user selected
codex
claude
EOF

INIT="$(cd .. && pwd)/bin/consult-init.sh"
LIB="$(cd .. && pwd)/lib/state.sh"
RH=$(bash -c "source '$LIB'; cw_repo_hash")

TOPIC=$("$INIT" "v018 active subset wins")
TD="$CLONE_WARS_HOME/state/$RH/$TOPIC"

assert_file_exists "$TD/_consult/troopers.txt" "troopers.txt written"
TROOPERS_BODY=$(grep -vE '^[[:space:]]*(#|$)' "$TD/_consult/troopers.txt")
# Expect 2 rows (codex+claude), opencode dropped.
ROW_COUNT=$(echo "$TROOPERS_BODY" | wc -l)
assert_eq "$ROW_COUNT" "2" "active subset produces N=2 roster"

# Provider column (first column) must be codex + claude only.
echo "$TROOPERS_BODY" | grep -qE $'^codex\t'    || { echo "FAIL: codex row missing"     >&2; exit 1; }
echo "$TROOPERS_BODY" | grep -qE $'^claude\t'   || { echo "FAIL: claude row missing"    >&2; exit 1; }
echo "$TROOPERS_BODY" | grep -qE $'^opencode\t' && { echo "FAIL: opencode should not be in roster" >&2; exit 1; } || true

pass "bin/consult-init.sh prefers providers-active.txt over providers-available.txt"
